version: '3.8'
services:
  backstage:
    image: backstage
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '8009:7007'
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backstage
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
