# Stage 1 - Base stage to install dependencies
FROM node:18-bullseye-slim as base
WORKDIR /app
COPY package.json yarn.lock ./

# Install Python and build-essential for node-gyp
RUN apt-get update && apt-get install -y python3 python3-pip build-essential
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN yarn install --frozen-lockfile
